# Lab | Numpy Deep Dive

### 1. Import the NUMPY package under the name np.


In [1]:
import numpy as np



### 2. Print the NUMPY version and the configuration.


In [7]:
print(np.show_config())
print(np.__version__)

{
  "Compilers": {
    "c": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35228",
      "commands": "cl"
    },
    "cython": {
      "name": "cython",
      "linker": "cython",
      "version": "3.2.9",
      "commands": "cython"
    },
    "c++": {
      "name": "msvc",
      "linker": "link",
      "version": "19.44.35228",
      "commands": "cl"
    }
  },
  "Machine Information": {
    "host": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    },
    "build": {
      "cpu": "x86_64",
      "family": "x86_64",
      "endian": "little",
      "system": "windows"
    }
  },
  "Build Dependencies": {
    "blas": {
      "name": "scipy-openblas",
      "found": true,
      "version": "0.3.34.0.0",
      "detection method": "pkgconfig",
      "include directory": "C:/Users/runneradmin/AppData/Local/Temp/cibw-run-l0z84qdl/cp314-win_amd64/build/venv/Lib/site-packages/scipy_openblas64/include",
      "lib dir

c:\Users\zoed\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages\numpy\__config__.py:155: UserWarning: Install `pyyaml` for better output
  warnings.warn("Install `pyyaml` for better output", stacklevel=1)


### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable "a"
Challenge: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?


In [ ]:
a = np.random.random(size=(2,3,5))


### 4. Print a.


In [9]:
print(a)

[[[0.3962229  0.74016821 0.37324514 0.77967006 0.16602753]
  [0.78787388 0.97428111 0.45281458 0.28559801 0.49742308]
  [0.05359534 0.00934434 0.06474316 0.18504713 0.62464571]]

 [[0.64294363 0.38991414 0.95488719 0.555544   0.9384542 ]
  [0.68555141 0.67788387 0.96003364 0.44764867 0.84518238]
  [0.34952631 0.64407439 0.84789637 0.35034538 0.00720741]]]


### 5. Create a 5x2x3 3-dimensional array with all values equaling 1.
### Assign the array to variable "b"


In [13]:
b = np.ones((5,2,3))


### 6. Print b.


In [14]:
print(b)


[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]



### 7. Do a and b have the same size? How do you prove that in Python code?


In [16]:
a.size == b.size


True


### 8. Are you able to add a and b? Why or why not?


In [ ]:
ab = a + b
# a and b can ot be added together because they are of different dimensions

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 



### 9. Transpose b so that it has the same structure of a (i.e. become a 2x3x5 array). Assign the transposed array to varialbe "c".


In [22]:
c = np.reshape(b, (2,3,5))
print(c)

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]



### 10. Try to add a and c. Now it should work. Assign the sum to variable "d". But why does it work now?


In [ ]:
d = a + c
print(d)
# It works now because both are 2x3x5 dimensional arrays. 

[[[1.3962229  1.74016821 1.37324514 1.77967006 1.16602753]
  [1.78787388 1.97428111 1.45281458 1.28559801 1.49742308]
  [1.05359534 1.00934434 1.06474316 1.18504713 1.62464571]]

 [[1.64294363 1.38991414 1.95488719 1.555544   1.9384542 ]
  [1.68555141 1.67788387 1.96003364 1.44764867 1.84518238]
  [1.34952631 1.64407439 1.84789637 1.35034538 1.00720741]]]



### 11. Print a and d. Notice the difference and relation of the two array in terms of the values? Explain.


In [ ]:
print(a , d)
# 1 has been added to every value of a, because c is an arry with only the number 1.


[[[0.3962229  0.74016821 0.37324514 0.77967006 0.16602753]
  [0.78787388 0.97428111 0.45281458 0.28559801 0.49742308]
  [0.05359534 0.00934434 0.06474316 0.18504713 0.62464571]]

 [[0.64294363 0.38991414 0.95488719 0.555544   0.9384542 ]
  [0.68555141 0.67788387 0.96003364 0.44764867 0.84518238]
  [0.34952631 0.64407439 0.84789637 0.35034538 0.00720741]]] [[[1.3962229  1.74016821 1.37324514 1.77967006 1.16602753]
  [1.78787388 1.97428111 1.45281458 1.28559801 1.49742308]
  [1.05359534 1.00934434 1.06474316 1.18504713 1.62464571]]

 [[1.64294363 1.38991414 1.95488719 1.555544   1.9384542 ]
  [1.68555141 1.67788387 1.96003364 1.44764867 1.84518238]
  [1.34952631 1.64407439 1.84789637 1.35034538 1.00720741]]]



### 12. Multiply a and c. Assign the result to e.


In [26]:
e = a*c



### 13. Does e equal to a? Why or why not?


In [ ]:
e == a
# e is equal to a because a has been multiplied by c which is an array containing only the number 1. a*1=a


array([[[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]],

       [[ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True],
        [ True,  True,  True,  True,  True]]])



### 14. Identify the max, min, and mean values in d. Assign those values to variables "d_max", "d_min", and "d_mean"


In [31]:
d_max = np.max(d)
d_min = np.min(d)
d_mean = np.mean(d)
print(d_max, d_min, d_mean)


1.9742811051608982 1.0072074089113503 1.5229264394448425



### 15. Now we want to label the values in d. First create an empty array "f" with the same shape (i.e. 2x3x5) as d using `np.empty`.


In [38]:
f = np.empty((2,3,5))




### 16. Populate the values in f. For each value in d, if it's larger than d_min but smaller than d_mean, assign 25 to the corresponding value in f.
If a value in d is larger than d_mean but smaller than d_max, assign 75 to the corresponding value in f.
If a value equals to d_mean, assign 50 to the corresponding value in f.
Assign 0 to the corresponding value(s) in f for d_min in d.
Assign 100 to the corresponding value(s) in f for d_max in d.
In the end, f should have only the following values: 0, 25, 50, 75, and 100.
Note: you don't have to use Numpy in this question.



In [44]:
for i,j,k in np.ndindex(d.shape):
    if (d[i, j, k] > d_min) and (d[i, j, k] < d_mean):
        f[i, j, k] = 25
    if (d[i, j, k] > d_mean) and (d[i, j, k] < d_max):
        f[i, j, k] = 75
    if d[i, j, k] == d_mean:
        f[i, j, k] = 50
    if d[i, j, k] == d_min:
        f[i, j, k] = 0
    if d[i, j, k] == d_max:
        f[i, j, k] = 100






### 17. Print d and f. Do you have your expected f?
For instance, if your d is:
array([[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
        [1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
        [1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],

       [[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
        [1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
        [1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]])

Your f should be:
array([[[ 75.,  75.,  75.,  25.,  75.],
        [ 75.,  75.,  25.,  25.,  25.],
        [ 75.,  25.,  75.,  75.,  75.]],

       [[ 25.,  25.,  25.,  25., 100.],
        [ 75.,  75.,  75.,  75.,  75.],
        [ 25.,  75.,   0.,  75.,  75.]]])



In [46]:
print(d)
print(f)

[[[1.3962229  1.74016821 1.37324514 1.77967006 1.16602753]
  [1.78787388 1.97428111 1.45281458 1.28559801 1.49742308]
  [1.05359534 1.00934434 1.06474316 1.18504713 1.62464571]]

 [[1.64294363 1.38991414 1.95488719 1.555544   1.9384542 ]
  [1.68555141 1.67788387 1.96003364 1.44764867 1.84518238]
  [1.34952631 1.64407439 1.84789637 1.35034538 1.00720741]]]
[[[ 25.  75.  25.  75.  25.]
  [ 75. 100.  25.  25.  25.]
  [ 25.  25.  25.  25.  75.]]

 [[ 75.  25.  75.  75.  75.]
  [ 75.  75.  75.  25.  75.]
  [ 25.  75.  75.  25.   0.]]]


### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), how to use string values 
("A", "B", "C", "D", and "E") to label the array elements? You are expecting the result to be:
array([[[ 'D',  'D',  'D',  'B',  'D'],
        [ 'D',  'D',  'B',  'B',  'B'],
        [ 'D',  'B',  'D',  'D',  'D']],

       [[ 'B',  'B',  'B',  'B',  'E'],
        [ 'D',  'D',  'D',  'D',  'D'],
        [ 'B',  'D',   'A',  'D', 'D']]])
Again, you don't need Numpy in this question.

In [49]:
g = np.empty((2,3,5), dtype= str)
for i,j,k in np.ndindex(d.shape):
    if (d[i, j, k] > d_min) and (d[i, j, k] < d_mean):
        g[i, j, k] = "B"
    if (d[i, j, k] > d_mean) and (d[i, j, k] < d_max):
        g[i, j, k] = "D"
    if d[i, j, k] == d_mean:
        g[i, j, k] = "C"
    if d[i, j, k] == d_min:
        g[i, j, k] = "A"
    if d[i, j, k] == d_max:
        g[i, j, k] = "E"

print(g)

[[['B' 'D' 'B' 'D' 'B']
  ['D' 'E' 'B' 'B' 'B']
  ['B' 'B' 'B' 'B' 'D']]

 [['D' 'B' 'D' 'D' 'D']
  ['D' 'D' 'D' 'B' 'D']
  ['B' 'D' 'D' 'B' 'A']]]
